// Mock feedback data
export const mockFeedbacks = [
  {
    id: 1,
    title: "Feature Request",
    message: "It would be great to have a dark mode in the app.",
    source: "Google Forms",
    status: "Pending",
    date: "2025-08-25",
  },
  {
    id: 2,
    title: "Bug Report",
    message: "The dashboard takes too long to load on mobile.",
    source: "Typeform",
    status: "Reviewed",
    date: "2025-08-20",
  },
  {
    id: 3,
    title: "General Feedback",
    message: "Loving the UI, very clean and intuitive!",
    source: "SurveyMonkey",
    status: "Resolved",
    date: "2025-08-15",
  },
  {
    id: 4,
    title: "Bug Report",
    message: "The dashboard takes too long to load on mobile.",
    source: "Typeform",
    status: "Reviewed",
    date: "2025-08-20",
  },
  {
    id: 5,
    title: "General Feedback",
    message: "Loving the UI, very clean and intuitive!",
    source: "SurveyMonkey",
    status: "Resolved",
    date: "2025-08-15",
  },
  {
    id: 6,
    title: "Bug Report",
    message: "The dashboard takes too long to load on mobile.",
    source: "Typeform",
    status: "Reviewed",
    date: "2025-08-20",
  },
  {
    id: 7,
    title: "General Feedback",
    message: "Loving the UI, very clean and intuitive!",
    source: "SurveyMonkey",
    status: "Resolved",
    date: "2025-08-15",
  },
];